Prof. Fernando Amaral

www.eia.ai

# Machine Learning

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.ensemble import RandomForestClassifier

In [ ]:
credito = pd.read_csv('Credit.csv')
credito.head()

,checking_status,duration,credit_history,purpose,credit_amount,savings_status,employment,installment_commitment,personal_status,other_parties,...,property_magnitude,age,other_payment_plans,housing,existing_credits,job,num_dependents,own_telephone,foreign_worker,class
0,<0,6,'critical/other existing credit',radio/tv,1169,'no known savings',>=7,4,'male single',none,...,'real estate',67,none,own,2,skilled,1,yes,yes,good
1,0<=X<200,48,'existing paid',radio/tv,5951,<100,1<=X<4,2,'female div/dep/mar',none,...,'real estate',22,none,own,1,skilled,1,none,yes,bad
2,'no checking',12,'critical/other existing credit',education,2096,<100,4<=X<7,2,'male single',none,...,'real estate',49,none,own,1,'unskilled resident',2,none,yes,good
3,<0,42,'existing paid',furniture/equipment,7882,<100,4<=X<7,2,'male single',guarantor,...,'life insurance',45,none,'for free',1,skilled,2,none,yes,good
4,<0,24,'delayed previously','new car',4870,<100,1<=X<4,3,'male single',none,...,'no known property',53,none,'for free',2,skilled,2,none,yes,bad

In [ ]:
labelencoder = LabelEncoder()
for i in credito.select_dtypes(include='object'):
  if i != 'class':
    credito[i] = labelencoder.fit_transform(credito[i])

In [ ]:
credito.head()

,checking_status,duration,credit_history,purpose,credit_amount,savings_status,employment,installment_commitment,personal_status,other_parties,...,property_magnitude,age,other_payment_plans,housing,existing_credits,job,num_dependents,own_telephone,foreign_worker,class
0,2,6,1,7,1169,0,3,4,3,2,...,2,67,1,1,2,3,1,1,1,good
1,1,48,3,7,5951,3,0,2,0,2,...,2,22,1,1,1,3,1,0,1,bad
2,0,12,1,4,2096,3,1,2,3,2,...,2,49,1,1,1,2,2,0,1,good
3,2,42,3,5,7882,3,1,2,3,1,...,0,45,1,0,1,3,2,0,1,good
4,2,24,2,1,4870,3,0,3,3,2,...,1,53,1,0,2,3,2,0,1,bad

In [ ]:
previsores = credito.iloc[:,0:20].values
classe = credito.iloc[:,20].values

In [ ]:
previsores

array([[ 2,  6,  1, ...,  1,  1,  1],
       [ 1, 48,  3, ...,  1,  0,  1],
       [ 0, 12,  1, ...,  2,  0,  1],
       ...,
       [ 0, 12,  3, ...,  1,  0,  1],
       [ 2, 45,  3, ...,  1,  1,  1],
       [ 1, 45,  1, ...,  1,  0,  1]])

In [ ]:
print(type(classe))

<class 'numpy.ndarray'>

In [ ]:
X_treinamento, X_teste, y_treinamento, y_teste = train_test_split(previsores, classe, test_size=0.3, random_state=0)

In [ ]:
print(X_treinamento.shape)
print(X_teste.shape)
print(y_treinamento.shape)
print(y_teste.shape)

(700, 20)
(300, 20)
(700,)
(300,)

In [ ]:
floresta = RandomForestClassifier(n_estimators = 500,random_state=0)
floresta.fit(X_treinamento,y_treinamento)

RandomForestClassifier(n_estimators=500, random_state=0)

In [ ]:
previsoes = floresta.predict(X_teste)
print(previsoes)

['bad' 'good' 'good' 'good' 'good' 'good' 'good' 'good' 'good' 'bad' 'bad'
 'good' 'good' 'good' 'bad' 'good' 'good' 'good' 'bad' 'good' 'good'
 'good' 'good' 'good' 'good' 'bad' 'good' 'good' 'good' 'bad' 'good'
 'good' 'good' 'good' 'good' 'bad' 'good' 'good' 'good' 'good' 'good'
 'bad' 'good' 'good' 'good' 'bad' 'good' 'bad' 'good' 'good' 'good' 'bad'
 'good' 'good' 'good' 'good' 'bad' 'good' 'good' 'good' 'bad' 'good'
 'good' 'good' 'good' 'good' 'good' 'good' 'bad' 'good' 'good' 'good'
 'bad' 'good' 'bad' 'good' 'good' 'good' 'good' 'good' 'good' 'good'
 'good' 'good' 'good' 'good' 'bad' 'good' 'good' 'good' 'good' 'good'
 'good' 'good' 'good' 'good' 'good' 'good' 'good' 'good' 'good' 'good'
 'good' 'good' 'good' 'good' 'bad' 'bad' 'bad' 'good' 'good' 'bad' 'bad'
 'good' 'good' 'good' 'good' 'good' 'good' 'good' 'good' 'good' 'good'
 'good' 'good' 'good' 'good' 'good' 'good' 'good' 'good' 'good' 'bad'
 'good' 'good' 'good' 'good' 'good' 'good' 'bad' 'bad' 'bad' 'good' 'good'
 'good' 'good' 'good' 'bad' 'good' 'good' 'good' 'good' 'good' 'good'
 'good' 'good' 'good' 'good' 'good' 'good' 'good' 'good' 'good' 'good'
 'bad' 'bad' 'bad' 'good' 'good' 'good' 'bad' 'good' 'bad' 'good' 'good'
 'bad' 'bad' 'bad' 'good' 'good' 'good' 'good' 'good' 'bad' 'good' 'good'
 'good' 'good' 'good' 'good' 'good' 'bad' 'good' 'good' 'good' 'good'
 'good' 'good' 'good' 'good' 'good' 'good' 'bad' 'bad' 'good' 'good' 'bad'
 'good' 'good' 'good' 'good' 'good' 'good' 'good' 'good' 'good' 'good'
 'good' 'good' 'bad' 'bad' 'good' 'good' 'good' 'good' 'good' 'good' 'bad'
 'bad' 'good' 'good' 'good' 'good' 'good' 'bad' 'bad' 'good' 'good' 'good'
 'good' 'good' 'good' 'good' 'good' 'good' 'good' 'good' 'good' 'good'
 'good' 'good' 'good' 'good' 'good' 'good' 'good' 'bad' 'good' 'good'
 'good' 'good' 'good' 'good' 'good' 'bad' 'bad' 'good' 'good' 'good'
 'good' 'bad' 'good' 'good' 'good' 'good' 'good' 'good' 'good' 'good'
 'good' 'good' 'good' 'good' 'good' 'good' 'good' 'good' 'good' 'good'
 'good' 'good' 'good' 'good' 'good' 'good' 'good' 'bad' 'good' 'bad' 'bad']

In [ ]:
confusao = confusion_matrix(y_teste,previsoes)
print(confusao)

[[ 37  49]
 [ 17 197]]

In [ ]:
taxa_acerto = accuracy_score(y_teste,previsoes)
print(taxa_acerto)

0.78